### PR TITLE
Attempt to fix travis

### PR DESCRIPTION
**Pull request by qnikst**
This PR is mainly for testing purposes, should not be merged if travis will not succeed.

### CODE REVIEW

**Comment by hyperthunk** [comment]
This failed on travis. One failure (for GHC 7.4) was due to a dependency that couldn't be resolved. The 7.6 release passed. The 7.8 failed but that was due to a known race condition - see https://github.com/haskell-distributed/distributed-process-supervisor/issues/1 for details. I am quite frankly, sick of travis builds failing due to being unable to resolve dependencies that are _obviously_ available on hackage. :/

**Comment by qnikst** [comment]
I tried to solve slightly different problem here, as before this patch travis run tests for `distributed-process` but not for `distributed-process-supervisor` and this PR is about fixing that, and not races that we will have to fix sometime then.

**Comment by qnikst** [comment]
@hyperthunk latest `distributed-process-tests` is not on a hackage yet, and few dependencies are bumped there, it should help cabal to find out build path.

**Comment by qnikst** [comment]
So, I think this PR worth merging :)

**Pull request merged**
